basePath: /api/v1
definitions:
  handler.ErrorResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  request.GetJWTRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  request.RegisterUserRequest:
    properties:
      birthdate:
        type: string
      document:
        type: string
      email:
        type: string
      last_name:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  response.JWTResponse:
    properties:
      access_token:
        type: string
    type: object
  response.UserResponse:
    properties:
      birth_date:
        type: string
      document:
        type: string
      email:
        type: string
      id:
        type: string
      last_name:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: danilo.kodavara@gmail.com
    name: Danilo Kodavara
    url: https://www.linkedin.com/in/danilo-kodavara/
  description: API para cadastro de usuário
  license:
    name: Danilo  Kodavara License
    url: https://www.linkedin.com/in/danilo-kodavara/
  termsOfService: http://swagger.io/terms/
  title: Cadastro de Usuário API
  version: v1
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register User
      parameters:
      - description: register-user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
      summary: Register User
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Find By UserId
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Bearer token
        in: path
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
      security:
      - ApiKeyAuth: []
      summary: Find By UserId
      tags:
      - users
  /users/auth:
    post:
      consumes:
      - application/json
      description: Get JWT
      parameters:
      - description: user-credentials request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.GetJWTRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JWTResponse'
        "400":
          description: Bad Request
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "404":
          description: Not Found
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/handler.ErrorResponse'
            type: array
      summary: Get JWT
      tags:
      - jwt
swagger: "2.0"
