POST {{host}}{{base-path}}/users/auth
Content-Type: application/json

{
  "email": "dyk@email.com",
  "password": "d@nil0"
}

> {%
    client.global.set("token", response.body.access_token);
%}


###

POST {{host}}{{base-path}}/users
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Danilo",
  "last_name": "Kodavara",
  "email": "dyk@email.com",
  "document": "123456",
  "birthdate": "1991-01-24",
  "password": "d@nil0"
}

###

GET {{host}}{{base-path}}/users/{{id}}
Content-Type: application/json
Authorization: {{token}}
