basePath: /api/v1
host: localhost:8081
info:
  contact:
    email: danilo.kodavara@gmail.com
    name: Danilo Kodavara
    url: https://www.linkedin.com/in/danilo-kodavara/
  description: API para cadastro de usuário
  license:
    name: Danilo  Kodavara License
    url: https://www.linkedin.com/in/danilo-kodavara/
  termsOfService: http://swagger.io/terms/
  title: Cadastro de Usuário API
  version: v1
paths: {}
swagger: "2.0"
